### ISSUE TITLE
Featurelayer

### ISSUE THREAD

**Issue by abdel-abdelrazek** [Esri/react-arcgis#76]
when I add Featurelayer to the map it is rendered correctly in development mode in all browser, but when I build the project it does so only in chrome and Edge but not in IE11, 
So kindly if there is something I should do to have it working in IE11, I will be grateful if you let me know.

**Comment by jgravois** [comment]
do you see the same issue in a simple app thats loads the API from our CDN?

https://developers.arcgis.com/javascript/latest/sample-code/layers-featurelayer/index.html

**Comment by abdel-abdelrazek** [comment]
Mr. gravois, Thank you so much for your reply.
Unfortunately yes, it is the same behavior even if i used this Featurelayer

**Comment by jgravois** [comment]
i assume this is because of the default support for WebGL introduced in version 4.10.

https://developers.arcgis.com/javascript/latest/guide/release-notes/4.9/index.html#webgl-enabled-by-default-in-2d

i don't know any more than that though. i suggest you either contact customer support or use GeoNet if you need more help.

https://github.com/Esri/jsapi-resources/blob/master/SUPPORT.md
