### ISSUE TITLE
wanted: additional project maintainers/contributors (all experience levels welcome) 

### ISSUE THREAD

**Issue by jgravois** [Esri/react-arcgis#79]
even if you don't consider yourself an experienced React or ArcGIS API for JavaScript developer, this popular project is a great opportunity to get your hands as dirty as you want with some tech that continues to grow in popularity and help other developers 💻.

if you're willing, even sporadically, to review [issues](https://github.com/Esri/react-arcgis/issues), help with documentation or chip in with an enhancement request or bug fix, please click the <kbd>Watch</kbd> button and jump on in 🏊‍♀️!

the repository is a friendly place and i guarantee you'll learn something in the process 📚. 	

cc/ @NoashX, @odoe, ??

**Comment by tomwayson** [comment]
I'm in.

**Comment by jgravois** [comment]
@tomwayson thank goodness. i don't know _anything_ about React! 😹

**Comment by abdel-abdelrazek** [comment]
I'm in please.

**Comment by nicksenger** [comment]
:wave: @tomwayson 

Great to have you and @abdel-abdelrazek here. I've been MIA the past couple months but will try to be more active here if things come up.

**Comment by travisbutcher** [comment]
I am willing to start working on some pieces of this,  just getting my feet into the React and Typescript pools.

**Comment by tomwayson** [comment]
This is the only repo I've ever seen where there are more maintainers than open issues, and in fact, the only open issue is to solicit for more maintainers. 🤔 Could be a business model in there...

**Comment by agustin-pt** [comment]
I'd like to join!!

**Comment by tomrussell** [comment]
Are there any plans to offer React components for other modules in the JS API? Perhaps without the need to use the dojo module loading mechanism? We're building map apps that need deploying offline, with minimal external dependencies

I'd be happy to help contribute if there was interest in taking this on

**Comment by tomwayson** [comment]
Let me expand on:

> No, but feel free to propose modules you'd like to see in issues.

I think the primary value of this library is that it gets people up and running fast w/ commonly used components. Once you are up and running with those, you're probably better off writing one-off, purpose-built components that are specific to your application's needs. It is much harder to design a generic component that is useful in many different applications.

I'd say we're aiming for the 90/10 rule here. The 10% of the ArcGIS API that is useful to 90% of the users trying to get it into their React app. Maybe 95/5.

So if there is a component that would be useful to 90-95% of the people trying to get the ArcGIS API into their React application that is missing from this library, we want to hear about it, otherwise I think we're better off investing our time in ensuring that there's good documentation for how to create your own React component w/ esri-loader.

**Comment by tomrussell** [comment]
Hey @tomwayson, what I was hoping to find with this library was the ability to work with the components of the JS API without being tightly coupled to the ArcGIS Portal. The majority of our deployments include an ArcGIS installation, but some have an existing GIS platform that we would need to integrate with our products, having consistency and no external dependencies in our UI code could really help us streamline this.

I have seen the esri-loader has the ability to load modules from a self-hosted web server, but this being a React library I was wondering if React's own lazy loading and code-splitting features could be used for the same purpose as Dojo. I haven't done much of a deep-dive into the underpinnings of the JS API, so what I have in mind may not even be technically feasible, but it'd be great to have our React bundle completely self-contained.

Interested to hear your thoughts on this.

**Comment by jgravois** [comment]
y'all definitely appear to have things under control here.
