### ISSUE TITLE
Any alternatives to using loadModules.then?

### ISSUE THREAD

**Issue by ciesin-frank** [Esri/react-arcgis#87]
We're using version 4.0.0 of the @esri/react-arcgis npm package.

I have a question about using this package within a react project.

Is there a way, outside of using the loadModules function, to load modules that we need? 

For example, if we try to create a new Circle object outside of the 'loadModules.then' function, we get this error "'Circle' is not defined no-undef".  

If we try to import the Circle object from the react-arcgis package: 

import { Circle } from '@esri/react-arcgis'

We get this error: "Attempted import error: 'Circle' is not exported from '@esri/react-arcgis'.".

We also tried this:

import { Circle, Graphic } from 'esri-loader';

But then this code: 

            const circle = new Circle({
                center: center,
                radius: radius,
                radiusUnit: "meters"
            });

Causes this error:

TypeError: esri_loader__WEBPACK_IMPORTED_MODULE_9__.Circle is not a constructor

We totally understand we may have to use the loadModules function to load the modules we need, but we're wondering if there's another, perhaps simpler way.

Thanks.

**Comment by abdel-abdelrazek** [comment]
Have a look on that package
https://www.npmjs.com/package/@arcgis/webpack-plugin

**Comment by ciesin-frank** [comment]
We're currently using the create-react-app and the @esri/react-arcgis packages.  Can this @arcgis/webpack-plugin package be used in addition or is it an alternative package?

**Comment by abdel-abdelrazek** [comment]
It is alternative package, it will enable you from importing esri staff like the following.
import SceneView from "esri/views/SceneView";

**Comment by ciesin-frank** [comment]
Thanks for the info.

**Comment by tomwayson** [comment]
@ciesin-frank 

You may have trouble using @arcgis/webpack-plugin w/ create-react-app: https://github.com/Esri/arcgis-webpack-plugin/issues/12

If so, you'll need to use esri-loader and/or react-arcgis, which means [you will not be able to `import` esri modules ](https://github.com/Esri/esri-loader#why-is-this-needed).

If your problem is that `loadModules()` is async, you might check out the patterns I link to here: https://github.com/Esri/esri-loader/issues/150
